/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { metadataFieldsDeleteMetadataFieldDatasource } from "../../funcs/metadataFieldsDeleteMetadataFieldDatasource.js";
import { DeleteMetadataFieldDatasourceRequestBody$zodSchema } from "../../models/deletemetadatafielddatasourceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  external_id: z.string().describe(
    "The external ID of the metadata field to update the datasource for.",
  ),
  RequestBody: DeleteMetadataFieldDatasourceRequestBody$zodSchema,
};

export const tool$metadataFieldsDeleteMetadataFieldDatasource: ToolDefinition<
  typeof args
> = {
  name: "delete-metadata-datasource-values",
  description:
    `Removes one or more allowed values from a metadata field's datasource

Removes specific values from a metadata field's datasource by their external IDs.`,
  scopes: ["builder"],
  annotations: {
    "title": "Delete Metadata Datasource Values",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsDeleteMetadataFieldDatasource(
      client,
      args.external_id,
      args.RequestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
