/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { metadataFieldsUpdateMetadataField } from "../../funcs/metadataFieldsUpdateMetadataField.js";
import { MetadataField$zodSchema } from "../../models/metadatafield.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  external_id: z.string().describe(
    "The external ID of the metadata field to retrieve.",
  ),
  metadata_field: MetadataField$zodSchema,
};

export const tool$metadataFieldsUpdateMetadataField: ToolDefinition<
  typeof args
> = {
  name: "update-metadata-field",
  description: `Updates the configuration of an existing metadata field

Updates the properties and configuration of the specified metadata field.`,
  scopes: ["admin"],
  annotations: {
    "title": "Update Metadata Field",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsUpdateMetadataField(
      client,
      args.external_id,
      args.metadata_field,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
