/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { metadataFieldsUpdateMetadataFieldDatasource } from "../../funcs/metadataFieldsUpdateMetadataFieldDatasource.js";
import { UpdateMetadataFieldDatasourceRequestBody$zodSchema } from "../../models/updatemetadatafielddatasourceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  external_id: z.string().describe(
    "The external ID of the metadata field to update the datasource for.",
  ),
  RequestBody: UpdateMetadataFieldDatasourceRequestBody$zodSchema,
};

export const tool$metadataFieldsUpdateMetadataFieldDatasource: ToolDefinition<
  typeof args
> = {
  name: "update-metadata-datasource-values",
  description:
    `Updates the allowed values (the datasource) for a specified metadata field

Updates the values in a metadata field's datasource, including adding, modifying, or changing the order of values.`,
  scopes: ["builder"],
  annotations: {
    "title": "Update Metadata Datasource Values",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsUpdateMetadataFieldDatasource(
      client,
      args.external_id,
      args.RequestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
