/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKOptions } from "../lib/config.js";
import { MCPScope } from "./scopes.js";

/**
 * Base flags interface for MCP server configuration.
 * Used by both CLI start command and Gram deployment wrapper.
 */
export interface MCPServerFlags {
  readonly tool?: string[];
  readonly mode?: "dynamic" | undefined;
  readonly scope?: MCPScope[];
  readonly "api-key"?: string | undefined;
  readonly "api-secret"?: string | undefined;
  readonly oauth2?: string | undefined;
  readonly "cloud-name"?: SDKOptions["cloud_name"] | undefined;
  readonly "server-url"?: string | undefined;
  readonly "server-index"?: SDKOptions["serverIdx"];
  readonly region?: SDKOptions["region"];
  readonly "api-host"?: SDKOptions["host"];
}
