/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Available scopes for the  OAuth 2.0 scheme (authorizationCode flow).
 *
 * @remarks
 * OAuth2 Authorization Code flow for user authentication
 */
export type OAuth2Scope =
  /**
   * Allows managing assets, including reading, updating, and deleting.
   */
  | "asset_management"
  /**
   * Allows uploading new assets.
   */
  | "upload";
