/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type CreateMetadataFieldGlobals = { cloud_name?: string | undefined };

export const CreateMetadataFieldGlobals$zodSchema: z.ZodType<
  CreateMetadataFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateMetadataFieldResponse = MetadataField | ApiError;

export const CreateMetadataFieldResponse$zodSchema: z.ZodType<
  CreateMetadataFieldResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  MetadataField$zodSchema,
  ApiError$zodSchema,
]);
