/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataRuleResponse,
  MetadataRuleResponse$zodSchema,
} from "./metadataruleresponse.js";

export type CreateMetadataRuleGlobals = { cloud_name?: string | undefined };

export const CreateMetadataRuleGlobals$zodSchema: z.ZodType<
  CreateMetadataRuleGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateMetadataRuleResponse = ApiError | MetadataRuleResponse;

export const CreateMetadataRuleResponse$zodSchema: z.ZodType<
  CreateMetadataRuleResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  MetadataRuleResponse$zodSchema,
]);
