/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DatasourceExternalIdsRequest = { external_ids: Array<string> };

export const DatasourceExternalIdsRequest$zodSchema: z.ZodType<
  DatasourceExternalIdsRequest
> = z.object({
  external_ids: z.array(z.string()).describe(
    "The external IDs of the datasource values.",
  ),
});
