/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DatasourceSearchRequest = {
  term?: string | undefined;
  max_results?: number | undefined;
};

export const DatasourceSearchRequest$zodSchema: z.ZodType<
  DatasourceSearchRequest
> = z.object({
  max_results: z.int().default(100).describe(
    "The maximum number of results to return.",
  ),
  term: z.string().optional().describe(
    "The term to search for. Can be any substring of the value.",
  ),
});
