/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DatasourceSearchInFieldRequest = {
  payload?: { [k: string]: any } | undefined;
};

export const DatasourceSearchInFieldRequest$zodSchema: z.ZodType<
  DatasourceSearchInFieldRequest
> = z.object({
  payload: z.record(z.string(), z.any()).optional().describe(
    "Metadata payload for rule-based inference.",
  ),
});
