/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 25522fc96eb9
 */

import * as z from "zod";

export type DatasourceSearchResult = {
  field_id?: string | undefined;
  id?: string | undefined;
  value?: string | undefined;
};

export const DatasourceSearchResult$zodSchema: z.ZodType<
  DatasourceSearchResult
> = z.object({
  field_id: z.string().optional().describe(
    "The external ID of the metadata field.",
  ),
  id: z.string().optional().describe("The external ID of the option."),
  value: z.string().optional().describe("The value of the option."),
});
