/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { StateEnum, StateEnum$zodSchema } from "./stateenum.js";

export type DatasourceValueInput = {
  external_id?: string | undefined;
  value?: string | undefined;
  position?: number | undefined;
  state?: StateEnum | undefined;
};

export const DatasourceValueInput$zodSchema: z.ZodType<DatasourceValueInput> = z
  .object({
    external_id: z.string().optional().describe(
      "The external ID of the datasource value.",
    ),
    position: z.int().optional().describe("The position of the option."),
    state: StateEnum$zodSchema.optional().describe(
      "The active or inactive state.",
    ),
    value: z.string().optional().describe("The value of the option."),
  });
