/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MessageResponse,
  MessageResponse$zodSchema,
} from "./messageresponse.js";

export type DeleteMetadataFieldGlobals = { cloud_name?: string | undefined };

export const DeleteMetadataFieldGlobals$zodSchema: z.ZodType<
  DeleteMetadataFieldGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteMetadataFieldRequest = { external_id: string };

export const DeleteMetadataFieldRequest$zodSchema: z.ZodType<
  DeleteMetadataFieldRequest
> = z.object({
  external_id: z.string().describe("The external ID of the metadata field."),
});

export type DeleteMetadataFieldResponse = MessageResponse | ApiError;

export const DeleteMetadataFieldResponse$zodSchema: z.ZodType<
  DeleteMetadataFieldResponse
> = z.union([
  MessageResponse$zodSchema,
  ApiError$zodSchema,
]);
