/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type DeleteMetadataFieldGlobals = { cloud_name?: string | undefined };

export const DeleteMetadataFieldGlobals$zodSchema: z.ZodType<
  DeleteMetadataFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteMetadataFieldRequest = { external_id: string };

export const DeleteMetadataFieldRequest$zodSchema: z.ZodType<
  DeleteMetadataFieldRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string().describe(
    "The external ID of the metadata field to retrieve.",
  ),
});

/**
 * metadata field deleted
 */
export type DeleteMetadataFieldResponseBody = { message: string };

export const DeleteMetadataFieldResponseBody$zodSchema: z.ZodType<
  DeleteMetadataFieldResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("metadata field deleted");

export type DeleteMetadataFieldResponse =
  | DeleteMetadataFieldResponseBody
  | ApiError;

export const DeleteMetadataFieldResponse$zodSchema: z.ZodType<
  DeleteMetadataFieldResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteMetadataFieldResponseBody$zodSchema),
  ApiError$zodSchema,
]);
