/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type DeleteMetadataRuleGlobals = { cloud_name?: string | undefined };

export const DeleteMetadataRuleGlobals$zodSchema: z.ZodType<
  DeleteMetadataRuleGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteMetadataRuleRequest = { external_id: string };

export const DeleteMetadataRuleRequest$zodSchema: z.ZodType<
  DeleteMetadataRuleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string().describe(
    "The unique identifier of the metadata rule.",
  ),
});

/**
 * metadata rule deleted.
 */
export type DeleteMetadataRuleResponseBody = { success: boolean };

export const DeleteMetadataRuleResponseBody$zodSchema: z.ZodType<
  DeleteMetadataRuleResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
}).describe("metadata rule deleted.");

export type DeleteMetadataRuleResponse =
  | DeleteMetadataRuleResponseBody
  | ApiError;

export const DeleteMetadataRuleResponse$zodSchema: z.ZodType<
  DeleteMetadataRuleResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteMetadataRuleResponseBody$zodSchema),
  ApiError$zodSchema,
]);
