/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type DeleteMetadataRuleGlobals = { cloud_name?: string | undefined };

export const DeleteMetadataRuleGlobals$zodSchema: z.ZodType<
  DeleteMetadataRuleGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteMetadataRuleRequest = { external_id: string };

export const DeleteMetadataRuleRequest$zodSchema: z.ZodType<
  DeleteMetadataRuleRequest
> = z.object({
  external_id: z.string().describe(
    "The unique identifier of the metadata rule.",
  ),
});

export type DeleteMetadataRuleResponse = SuccessResponse | ApiError;

export const DeleteMetadataRuleResponse$zodSchema: z.ZodType<
  DeleteMetadataRuleResponse
> = z.union([
  SuccessResponse$zodSchema,
  ApiError$zodSchema,
]);
