/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldDatasourceValuesArray,
  MetadataFieldDatasourceValuesArray$zodSchema,
} from "./metadatafielddatasourcevaluesarray.js";

export type DeleteMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteMetadataFieldDatasourceRequestBody = {
  external_ids: Array<string>;
};

export const DeleteMetadataFieldDatasourceRequestBody$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceRequestBody
> = z.object({
  external_ids: z.array(z.string()),
});

export type DeleteMetadataFieldDatasourceRequest = {
  external_id: string;
  RequestBody: DeleteMetadataFieldDatasourceRequestBody;
};

export const DeleteMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceRequest
> = z.object({
  RequestBody: z.lazy(() => DeleteMetadataFieldDatasourceRequestBody$zodSchema),
  external_id: z.string().describe(
    "The external ID of the metadata field to update the datasource for.",
  ),
});

export type DeleteMetadataFieldDatasourceResponse =
  | ApiError
  | MetadataFieldDatasourceValuesArray;

export const DeleteMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldDatasourceValuesArray$zodSchema,
]);
