/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DatasourceExternalIdsRequest,
  DatasourceExternalIdsRequest$zodSchema,
} from "./datasourceexternalidsrequest.js";
import {
  MetadataFieldDatasourceValuesArray,
  MetadataFieldDatasourceValuesArray$zodSchema,
} from "./metadatafielddatasourcevaluesarray.js";

export type DeleteMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteMetadataFieldDatasourceRequest = {
  external_id: string;
  datasource_external_ids_request: DatasourceExternalIdsRequest;
};

export const DeleteMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceRequest
> = z.object({
  datasource_external_ids_request: DatasourceExternalIdsRequest$zodSchema
    .describe("The datasource entry external IDs to delete."),
  external_id: z.string().describe(
    "The external ID of the metadata field to update the datasource for.",
  ),
});

export type DeleteMetadataFieldDatasourceResponse =
  | ApiError
  | MetadataFieldDatasourceValuesArray;

export const DeleteMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  DeleteMetadataFieldDatasourceResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldDatasourceValuesArray$zodSchema,
]);
