/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type GetMetadataFieldGlobals = { cloud_name?: string | undefined };

export const GetMetadataFieldGlobals$zodSchema: z.ZodType<
  GetMetadataFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetMetadataFieldRequest = { external_id: string };

export const GetMetadataFieldRequest$zodSchema: z.ZodType<
  GetMetadataFieldRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string().describe(
    "The external ID of the metadata field to retrieve.",
  ),
});

export type GetMetadataFieldResponse = MetadataField | ApiError;

export const GetMetadataFieldResponse$zodSchema: z.ZodType<
  GetMetadataFieldResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  MetadataField$zodSchema,
  ApiError$zodSchema,
]);
