/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type ListMetadataFieldsGlobals = { cloud_name?: string | undefined };

export const ListMetadataFieldsGlobals$zodSchema: z.ZodType<
  ListMetadataFieldsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListMetadataFieldsRequest = {
  external_ids?: Array<string> | undefined;
};

export const ListMetadataFieldsRequest$zodSchema: z.ZodType<
  ListMetadataFieldsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_ids: z.array(z.string()).describe(
    "The external IDs of the metadata fields to retrieve. if not provided, all metadata fields will be returned.",
  ).optional(),
});

/**
 * metadata fields retrieved
 */
export type ListMetadataFieldsResponseBody = {
  metadata_fields?: Array<MetadataField> | undefined;
};

export const ListMetadataFieldsResponseBody$zodSchema: z.ZodType<
  ListMetadataFieldsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata_fields: z.array(MetadataField$zodSchema).optional(),
}).describe("metadata fields retrieved");

export type ListMetadataFieldsResponse =
  | ApiError
  | ListMetadataFieldsResponseBody;

export const ListMetadataFieldsResponse$zodSchema: z.ZodType<
  ListMetadataFieldsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => ListMetadataFieldsResponseBody$zodSchema),
]);
