/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataRuleResponse,
  MetadataRuleResponse$zodSchema,
} from "./metadataruleresponse.js";

export type ListMetadataRulesGlobals = { cloud_name?: string | undefined };

export const ListMetadataRulesGlobals$zodSchema: z.ZodType<
  ListMetadataRulesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListMetadataRulesRequest = {};

export const ListMetadataRulesRequest$zodSchema: z.ZodType<
  ListMetadataRulesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/**
 * metadata rules retrieved.
 */
export type ListMetadataRulesResponseBody = {
  metadata_rules?: Array<MetadataRuleResponse> | undefined;
};

export const ListMetadataRulesResponseBody$zodSchema: z.ZodType<
  ListMetadataRulesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata_rules: z.array(MetadataRuleResponse$zodSchema).optional(),
}).describe("metadata rules retrieved.");

export type ListMetadataRulesResponse =
  | ApiError
  | ListMetadataRulesResponseBody;

export const ListMetadataRulesResponse$zodSchema: z.ZodType<
  ListMetadataRulesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => ListMetadataRulesResponseBody$zodSchema),
]);
