/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldsListResponse,
  MetadataFieldsListResponse$zodSchema,
} from "./metadatafieldslistresponse.js";

export type ListMetadataFieldsGlobals = { cloud_name?: string | undefined };

export const ListMetadataFieldsGlobals$zodSchema: z.ZodType<
  ListMetadataFieldsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListMetadataFieldsRequest = {
  external_ids?: Array<string> | undefined;
};

export const ListMetadataFieldsRequest$zodSchema: z.ZodType<
  ListMetadataFieldsRequest
> = z.object({
  external_ids: z.array(z.string()).describe(
    "The external IDs of the metadata fields to retrieve. if not provided, all metadata fields will be returned.",
  ).optional(),
});

export type ListMetadataFieldsResponse = ApiError | MetadataFieldsListResponse;

export const ListMetadataFieldsResponse$zodSchema: z.ZodType<
  ListMetadataFieldsResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldsListResponse$zodSchema,
]);
