/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataRulesListResponse,
  MetadataRulesListResponse$zodSchema,
} from "./metadataruleslistresponse.js";

export type ListMetadataRulesGlobals = { cloud_name?: string | undefined };

export const ListMetadataRulesGlobals$zodSchema: z.ZodType<
  ListMetadataRulesGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListMetadataRulesRequest = {};

export const ListMetadataRulesRequest$zodSchema: z.ZodType<
  ListMetadataRulesRequest
> = z.object({});

export type ListMetadataRulesResponse = ApiError | MetadataRulesListResponse;

export const ListMetadataRulesResponse$zodSchema: z.ZodType<
  ListMetadataRulesResponse
> = z.union([
  ApiError$zodSchema,
  MetadataRulesListResponse$zodSchema,
]);
