/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ActionExp, ActionExp$zodSchema } from "./actionexp.js";
import { SmdCondition, SmdCondition$zodSchema } from "./smdcondition.js";

/**
 * The state of the rule.
 */
export const MetadataRuleUpdateState$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The state of the rule.");

export type MetadataRuleUpdateState = z.infer<
  typeof MetadataRuleUpdateState$zodSchema
>;

export type MetadataRuleUpdate = {
  metadata_field_id?: string | undefined;
  name?: string | undefined;
  condition?: SmdCondition | undefined;
  result?: ActionExp | undefined;
  state?: MetadataRuleUpdateState | undefined;
  position?: number | undefined;
};

export const MetadataRuleUpdate$zodSchema: z.ZodType<
  MetadataRuleUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: SmdCondition$zodSchema.optional(),
  metadata_field_id: z.string().optional(),
  name: z.string().optional(),
  position: z.number().int().optional(),
  result: ActionExp$zodSchema.optional(),
  state: MetadataRuleUpdateState$zodSchema.optional(),
});
