/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MetadataFieldDatasourceValue = {
  external_id?: string | undefined;
  value?: string | undefined;
};

export const MetadataFieldDatasourceValue$zodSchema: z.ZodType<
  MetadataFieldDatasourceValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string().optional(),
  value: z.string().optional(),
});
