/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e5674196796
 */

import * as z from "zod";
import {
  MetadataRuleResponse,
  MetadataRuleResponse$zodSchema,
} from "./metadataruleresponse.js";

export type MetadataRulesListResponse = {
  metadata_rules?: Array<MetadataRuleResponse> | undefined;
};

export const MetadataRulesListResponse$zodSchema: z.ZodType<
  MetadataRulesListResponse
> = z.object({
  metadata_rules: z.array(MetadataRuleResponse$zodSchema).optional(),
});
