/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of the metadata field.
 */
export const Type$zodSchema = z.enum([
  "string",
  "integer",
  "date",
  "enum",
  "set",
]).describe("The type of the metadata field.");

export type Type = z.infer<typeof Type$zodSchema>;

export type DefaultValue = string | number;

export const DefaultValue$zodSchema: z.ZodType<
  DefaultValue,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number().int(),
]);

/**
 * The validation defined for the metadata field.
 */
export type Validation = {};

export const Validation$zodSchema: z.ZodType<
  Validation,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("The validation defined for the metadata field.");

/**
 * The restrictions defined for the metadata field.
 */
export type Restrictions = { readonly_ui?: boolean | undefined };

export const Restrictions$zodSchema: z.ZodType<
  Restrictions,
  z.ZodTypeDef,
  unknown
> = z.object({
  readonly_ui: z.boolean().optional(),
}).describe("The restrictions defined for the metadata field.");

/**
 * The state of the option.
 */
export const MetadataFieldState$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The state of the option.");

export type MetadataFieldState = z.infer<typeof MetadataFieldState$zodSchema>;

export type MetadataFieldValue = {
  external_id?: string | undefined;
  value?: string | undefined;
  position?: number | undefined;
  state?: MetadataFieldState | undefined;
};

export const MetadataFieldValue$zodSchema: z.ZodType<
  MetadataFieldValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string().optional(),
  position: z.number().int().optional(),
  state: MetadataFieldState$zodSchema.optional(),
  value: z.string().optional(),
});

/**
 * The datasource defined for the metadata field.
 */
export type Datasource = { values?: Array<MetadataFieldValue> | undefined };

export const Datasource$zodSchema: z.ZodType<
  Datasource,
  z.ZodTypeDef,
  unknown
> = z.object({
  values: z.array(z.lazy(() => MetadataFieldValue$zodSchema)).optional(),
}).describe("The datasource defined for the metadata field.");

export type MetadataField = {
  type: Type;
  external_id?: string | undefined;
  label: string;
  mandatory?: boolean | null | undefined;
  default_value?: string | number | null | undefined;
  default_disabled?: boolean | null | undefined;
  validation?: Validation | null | undefined;
  restrictions?: Restrictions | null | undefined;
  datasource?: Datasource | null | undefined;
  allow_dynamic_list_values?: boolean | null | undefined;
};

export const MetadataField$zodSchema: z.ZodType<
  MetadataField,
  z.ZodTypeDef,
  unknown
> = z.object({
  allow_dynamic_list_values: z.boolean().nullable().optional(),
  datasource: z.lazy(() => Datasource$zodSchema).nullable().optional(),
  default_disabled: z.boolean().nullable().optional(),
  default_value: z.union([
    z.string(),
    z.number().int(),
  ]).nullable().optional(),
  external_id: z.string().optional(),
  label: z.string(),
  mandatory: z.boolean().nullable().optional(),
  restrictions: z.lazy(() => Restrictions$zodSchema).nullable().optional(),
  type: Type$zodSchema,
  validation: z.lazy(() => Validation$zodSchema).nullable().optional(),
});
