/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type MetadataFieldsListResponse = {
  metadata_fields?: Array<MetadataField> | undefined;
};

export const MetadataFieldsListResponse$zodSchema: z.ZodType<
  MetadataFieldsListResponse
> = z.object({
  metadata_fields: z.array(MetadataField$zodSchema).optional(),
});
