/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ActionExp, ActionExp$zodSchema } from "./actionexp.js";
import { SmdCondition, SmdCondition$zodSchema } from "./smdcondition.js";

/**
 * The state of the rule.
 */
export const MetadataRuleResponseState$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The state of the rule.");

export type MetadataRuleResponseState = z.infer<
  typeof MetadataRuleResponseState$zodSchema
>;

export type MetadataRuleResponse = {
  metadata_field_id?: string | undefined;
  name?: string | undefined;
  condition?: SmdCondition | undefined;
  result?: ActionExp | undefined;
  state?: MetadataRuleResponseState | undefined;
  position?: number | undefined;
  external_id?: string | undefined;
  condition_signature?: string | undefined;
};

export const MetadataRuleResponse$zodSchema: z.ZodType<
  MetadataRuleResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: SmdCondition$zodSchema.optional(),
  condition_signature: z.string().optional(),
  external_id: z.string().optional(),
  metadata_field_id: z.string().optional(),
  name: z.string().optional(),
  position: z.number().int().optional(),
  result: ActionExp$zodSchema.optional(),
  state: MetadataRuleResponseState$zodSchema.optional(),
});
