/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The condition that triggers this rule. Ensure it adheres to the metadata rule condition schema.
 */
export type MetadataRuleResponseCondition = {};

export const MetadataRuleResponseCondition$zodSchema: z.ZodType<
  MetadataRuleResponseCondition,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe(
  "The condition that triggers this rule. Ensure it adheres to the metadata rule condition schema.",
);

/**
 * The result to apply when the condition is met, should adhere to the metadata rule result schema.
 */
export type MetadataRuleResponseResult = {};

export const MetadataRuleResponseResult$zodSchema: z.ZodType<
  MetadataRuleResponseResult,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe(
  "The result to apply when the condition is met, should adhere to the metadata rule result schema.",
);

/**
 * The state of the rule.
 */
export const MetadataRuleResponseState$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The state of the rule.");

export type MetadataRuleResponseState = z.infer<
  typeof MetadataRuleResponseState$zodSchema
>;

export type MetadataRuleResponse = {
  metadata_field_id?: string | undefined;
  name?: string | undefined;
  condition?: MetadataRuleResponseCondition | undefined;
  result?: MetadataRuleResponseResult | undefined;
  state?: MetadataRuleResponseState | undefined;
  position?: number | undefined;
  external_id?: string | undefined;
  condition_signature?: string | undefined;
};

export const MetadataRuleResponse$zodSchema: z.ZodType<
  MetadataRuleResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: z.lazy(() => MetadataRuleResponseCondition$zodSchema).optional(),
  condition_signature: z.string().optional(),
  external_id: z.string().optional(),
  metadata_field_id: z.string().optional(),
  name: z.string().optional(),
  position: z.number().int().optional(),
  result: z.lazy(() => MetadataRuleResponseResult$zodSchema).optional(),
  state: MetadataRuleResponseState$zodSchema.optional(),
});
