/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MetadataFieldDatasourceValue,
  MetadataFieldDatasourceValue$zodSchema,
} from "./metadatafielddatasourcevalue.js";

export type MetadataFieldDatasourceValuesArray = {
  values?: Array<MetadataFieldDatasourceValue> | undefined;
};

export const MetadataFieldDatasourceValuesArray$zodSchema: z.ZodType<
  MetadataFieldDatasourceValuesArray,
  z.ZodTypeDef,
  unknown
> = z.object({
  values: z.array(MetadataFieldDatasourceValue$zodSchema).optional(),
});
