/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ActionExp, ActionExp$zodSchema } from "./actionexp.js";
import { SmdCondition, SmdCondition$zodSchema } from "./smdcondition.js";
import { StateEnum, StateEnum$zodSchema } from "./stateenum.js";

export type MetadataRuleCreate = {
  metadata_field_id: string;
  name: string;
  condition: SmdCondition;
  result: ActionExp;
  state?: StateEnum | undefined;
  position?: number | undefined;
};

export const MetadataRuleCreate$zodSchema: z.ZodType<MetadataRuleCreate> = z
  .object({
    condition: SmdCondition$zodSchema.describe(
      "The condition that triggers this metadata rule. Can be either a logical expression (and/or) or an atomic condition.",
    ),
    metadata_field_id: z.string().describe(
      "The ID of the metadata field this rule applies to.",
    ),
    name: z.string().describe("A descriptive name for the metadata rule."),
    position: z.int().optional().describe(
      "The position/order of this rule relative to other rules.",
    ),
    result: ActionExp$zodSchema.describe(
      "The result/action to apply when the condition is met.",
    ),
    state: StateEnum$zodSchema.optional().describe(
      "The active or inactive state.",
    ),
  });
