/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The condition that triggers this rule. Ensure it adheres to the metadata rule condition schema.
 */
export type MetadataRuleCreateCondition = {};

export const MetadataRuleCreateCondition$zodSchema: z.ZodType<
  MetadataRuleCreateCondition,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe(
  "The condition that triggers this rule. Ensure it adheres to the metadata rule condition schema.",
);

/**
 * The result to apply when the condition is met, should adhere to the metadata rule result schema.
 */
export type MetadataRuleCreateResult = {};

export const MetadataRuleCreateResult$zodSchema: z.ZodType<
  MetadataRuleCreateResult,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe(
  "The result to apply when the condition is met, should adhere to the metadata rule result schema.",
);

/**
 * The state of the rule.
 */
export const MetadataRuleCreateState$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The state of the rule.");

export type MetadataRuleCreateState = z.infer<
  typeof MetadataRuleCreateState$zodSchema
>;

export type MetadataRuleCreate = {
  metadata_field_id: string;
  name: string;
  condition: MetadataRuleCreateCondition;
  result: MetadataRuleCreateResult;
  state?: MetadataRuleCreateState | undefined;
  position?: number | undefined;
};

export const MetadataRuleCreate$zodSchema: z.ZodType<
  MetadataRuleCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: z.lazy(() => MetadataRuleCreateCondition$zodSchema),
  metadata_field_id: z.string(),
  name: z.string(),
  position: z.number().int().optional(),
  result: z.lazy(() => MetadataRuleCreateResult$zodSchema),
  state: MetadataRuleCreateState$zodSchema.optional(),
});
