/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { StateEnum, StateEnum$zodSchema } from "./stateenum.js";

/**
 * The type of the metadata field.
 */
export const Type = {
  String: "string",
  Integer: "integer",
  Date: "date",
  Enum: "enum",
  Set: "set",
} as const;
/**
 * The type of the metadata field.
 */
export type Type = ClosedEnum<typeof Type>;

export const Type$zodSchema = z.enum([
  "string",
  "integer",
  "date",
  "enum",
  "set",
]).describe("The type of the metadata field.");

/**
 * The default value of the metadata field.
 */
export type DefaultValue = string | number;

export const DefaultValue$zodSchema: z.ZodType<DefaultValue> = z.union([
  z.string(),
  z.int(),
]).describe("The default value of the metadata field.");

/**
 * Controls UI visibility and editability of the field. All three keys are always returned; any omitted key on input defaults to false.
 *
 * @remarks
 */
export type Restrictions = {
  readonly_ui?: boolean | undefined;
  hidden_ui?: boolean | undefined;
  excluded_from_search?: boolean | undefined;
};

export const Restrictions$zodSchema: z.ZodType<Restrictions> = z.object({
  excluded_from_search: z.boolean().optional().describe(
    "Whether the field is excluded from UI search by default.",
  ),
  hidden_ui: z.boolean().optional().describe(
    "Whether the field is hidden in the UI by default.",
  ),
  readonly_ui: z.boolean().optional().describe(
    "Whether the field is read-only in the UI. When true, the field can only be updated via the API.",
  ),
}).describe(
  "Controls UI visibility and editability of the field. All three keys are always returned; any omitted key on input defaults to false.\n",
);

export type MetadataFieldValue = {
  external_id?: string | undefined;
  value?: string | undefined;
  position?: number | undefined;
  state?: StateEnum | undefined;
};

export const MetadataFieldValue$zodSchema: z.ZodType<MetadataFieldValue> = z
  .object({
    external_id: z.string().optional().describe(
      "The external ID of the option.",
    ),
    position: z.int().optional().describe("The position of the option."),
    state: StateEnum$zodSchema.optional().describe(
      "The active or inactive state.",
    ),
    value: z.string().optional().describe("The value of the option."),
  });

/**
 * The datasource defined for the metadata field.
 */
export type Datasource = { values?: Array<MetadataFieldValue> | undefined };

export const Datasource$zodSchema: z.ZodType<Datasource> = z.object({
  values: z.array(z.lazy(() => MetadataFieldValue$zodSchema)).optional(),
}).describe("The datasource defined for the metadata field.");

export type MetadataField = {
  type?: Type | undefined;
  external_id?: string | undefined;
  label?: string | undefined;
  mandatory?: boolean | null | undefined;
  default_value?: string | number | null | undefined;
  default_disabled?: boolean | null | undefined;
  validation?: { [k: string]: any } | null | undefined;
  restrictions?: Restrictions | null | undefined;
  datasource?: Datasource | null | undefined;
  allow_dynamic_list_values?: boolean | null | undefined;
  alphabetically_sorted?: boolean | undefined;
};

export const MetadataField$zodSchema: z.ZodType<MetadataField> = z.object({
  allow_dynamic_list_values: z.boolean().nullable().optional().describe(
    "Whether the metadata field allows adding new options to the datasource dynamically.",
  ),
  alphabetically_sorted: z.boolean().optional().describe(
    "Whether datasource values are maintained in case-insensitive alphabetical order. When true, values are automatically sorted on insert and update. Default false.",
  ),
  datasource: z.lazy(() => Datasource$zodSchema).nullable().optional().describe(
    "The datasource defined for the metadata field.",
  ),
  default_disabled: z.boolean().nullable().optional().describe(
    "Whether the field is disabled in the UI by default.",
  ),
  default_value: z.union([
    z.string(),
    z.int(),
  ]).nullable().optional().describe("The default value of the metadata field."),
  external_id: z.string().optional().describe(
    "The external ID of the metadata field.",
  ),
  label: z.string().optional().describe("The label of the metadata field."),
  mandatory: z.boolean().nullable().optional().describe(
    "Whether the metadata field is mandatory.",
  ),
  restrictions: z.lazy(() => Restrictions$zodSchema).nullable().optional()
    .describe(
      "Controls UI visibility and editability of the field. All three keys are always returned; any omitted key on input defaults to false.\n",
    ),
  type: Type$zodSchema.optional().describe("The type of the metadata field."),
  validation: z.record(z.string(), z.any()).nullable().optional().describe(
    "The validation defined for the metadata field.",
  ),
});
