/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Whether to override existing options (override) or add to them (append). Default is append.
 */
export const OptionsExpMode = {
  Override: "override",
  Append: "append",
} as const;
/**
 * Whether to override existing options (override) or add to them (append). Default is append.
 */
export type OptionsExpMode = ClosedEnum<typeof OptionsExpMode>;

export const OptionsExpMode$zodSchema = z.enum([
  "override",
  "append",
]).describe(
  "Whether to override existing options (override) or add to them (append). Default is append.",
);

/**
 * Specifies which enum/set options to activate.
 */
export type OptionsExp = {
  external_ids: Array<string> | null;
  mode?: OptionsExpMode | undefined;
};

export const OptionsExp$zodSchema: z.ZodType<OptionsExp> = z.object({
  external_ids: z.array(z.string()).nullable(),
  mode: OptionsExpMode$zodSchema.default("append"),
}).describe("Specifies which enum/set options to activate.");
