/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Whether to override existing options (override) or add to them (append). Default is append.
 */
export const OptionsExpMode$zodSchema = z.enum([
  "override",
  "append",
]).describe(
  "Whether to override existing options (override) or add to them (append). Default is append.",
);

export type OptionsExpMode = z.infer<typeof OptionsExpMode$zodSchema>;

/**
 * Specifies which enum/set options to activate.
 */
export type OptionsExp = {
  external_ids: Array<string> | null;
  mode?: OptionsExpMode | undefined;
};

export const OptionsExp$zodSchema: z.ZodType<
  OptionsExp,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_ids: z.array(z.string()).nullable(),
  mode: OptionsExpMode$zodSchema.default("append"),
}).describe("Specifies which enum/set options to activate.");
