/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldsListResponse,
  MetadataFieldsListResponse$zodSchema,
} from "./metadatafieldslistresponse.js";
import {
  ReorderMetadataFieldRequest,
  ReorderMetadataFieldRequest$zodSchema,
} from "./reordermetadatafieldrequest.js";

export type ReorderMetadataFieldGlobals = { cloud_name?: string | undefined };

export const ReorderMetadataFieldGlobals$zodSchema: z.ZodType<
  ReorderMetadataFieldGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ReorderMetadataFieldRequestRequest = {
  external_id: string;
  reorder_metadata_field_request: ReorderMetadataFieldRequest;
};

export const ReorderMetadataFieldRequestRequest$zodSchema: z.ZodType<
  ReorderMetadataFieldRequestRequest
> = z.object({
  external_id: z.string().describe(
    "The external ID of the metadata field to reorder.",
  ),
  reorder_metadata_field_request: ReorderMetadataFieldRequest$zodSchema
    .describe("The new position for the metadata field."),
});

export type ReorderMetadataFieldResponse =
  | ApiError
  | MetadataFieldsListResponse;

export const ReorderMetadataFieldResponse$zodSchema: z.ZodType<
  ReorderMetadataFieldResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldsListResponse$zodSchema,
]);
