/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldsListResponse,
  MetadataFieldsListResponse$zodSchema,
} from "./metadatafieldslistresponse.js";

export type ReorderMetadataFieldsGlobals = { cloud_name?: string | undefined };

export const ReorderMetadataFieldsGlobals$zodSchema: z.ZodType<
  ReorderMetadataFieldsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ReorderMetadataFieldsResponse =
  | ApiError
  | MetadataFieldsListResponse;

export const ReorderMetadataFieldsResponse$zodSchema: z.ZodType<
  ReorderMetadataFieldsResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldsListResponse$zodSchema,
]);
