/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type ReorderMetadataFieldGlobals = { cloud_name?: string | undefined };

export const ReorderMetadataFieldGlobals$zodSchema: z.ZodType<
  ReorderMetadataFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ReorderMetadataFieldRequestBody = { position: number };

export const ReorderMetadataFieldRequestBody$zodSchema: z.ZodType<
  ReorderMetadataFieldRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  position: z.number().int(),
});

export type ReorderMetadataFieldRequest = {
  external_id: string;
  RequestBody: ReorderMetadataFieldRequestBody;
};

export const ReorderMetadataFieldRequest$zodSchema: z.ZodType<
  ReorderMetadataFieldRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() => ReorderMetadataFieldRequestBody$zodSchema),
  external_id: z.string().describe(
    "The external ID of the metadata field to reorder.",
  ),
});

/**
 * metadata fields reordered
 */
export type ReorderMetadataFieldResponseBody = {
  metadata_fields?: Array<MetadataField> | undefined;
};

export const ReorderMetadataFieldResponseBody$zodSchema: z.ZodType<
  ReorderMetadataFieldResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata_fields: z.array(MetadataField$zodSchema).optional(),
}).describe("metadata fields reordered");

export type ReorderMetadataFieldResponse =
  | ApiError
  | ReorderMetadataFieldResponseBody;

export const ReorderMetadataFieldResponse$zodSchema: z.ZodType<
  ReorderMetadataFieldResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => ReorderMetadataFieldResponseBody$zodSchema),
]);
