/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { DirectionEnum, DirectionEnum$zodSchema } from "./directionenum.js";

/**
 * The field to order by.
 */
export const OrderBy = {
  Label: "label",
  CreatedAt: "created_at",
  ExternalId: "external_id",
} as const;
/**
 * The field to order by.
 */
export type OrderBy = ClosedEnum<typeof OrderBy>;

export const OrderBy$zodSchema = z.enum([
  "label",
  "created_at",
  "external_id",
]).describe("The field to order by.");

export type ReorderMetadataFieldsRequest = {
  order_by: OrderBy;
  direction?: DirectionEnum | undefined;
};

export const ReorderMetadataFieldsRequest$zodSchema: z.ZodType<
  ReorderMetadataFieldsRequest
> = z.object({
  direction: DirectionEnum$zodSchema.optional().describe("Sort direction."),
  order_by: OrderBy$zodSchema.describe("The field to order by."),
});
