/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type ReorderMetadataFieldsGlobals = { cloud_name?: string | undefined };

export const ReorderMetadataFieldsGlobals$zodSchema: z.ZodType<
  ReorderMetadataFieldsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * The field to order by.
 */
export const OrderBy$zodSchema = z.enum([
  "label",
  "created_at",
  "external_id",
]).describe("The field to order by.");

export type OrderBy = z.infer<typeof OrderBy$zodSchema>;

/**
 * The direction to order by.
 */
export const Direction$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("The direction to order by.");

export type Direction = z.infer<typeof Direction$zodSchema>;

export type ReorderMetadataFieldsRequest = {
  order_by: OrderBy;
  direction?: Direction | undefined;
};

export const ReorderMetadataFieldsRequest$zodSchema: z.ZodType<
  ReorderMetadataFieldsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  direction: Direction$zodSchema.optional(),
  order_by: OrderBy$zodSchema,
});

/**
 * metadata fields reordered
 */
export type ReorderMetadataFieldsResponseBody = {
  metadata_fields?: Array<MetadataField> | undefined;
};

export const ReorderMetadataFieldsResponseBody$zodSchema: z.ZodType<
  ReorderMetadataFieldsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata_fields: z.array(MetadataField$zodSchema).optional(),
}).describe("metadata fields reordered");

export type ReorderMetadataFieldsResponse =
  | ApiError
  | ReorderMetadataFieldsResponseBody;

export const ReorderMetadataFieldsResponse$zodSchema: z.ZodType<
  ReorderMetadataFieldsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => ReorderMetadataFieldsResponseBody$zodSchema),
]);
