/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f5afe7656e0a
 */

import * as z from "zod";

export type ReorderMetadataFieldRequest = { position: number };

export const ReorderMetadataFieldRequest$zodSchema: z.ZodType<
  ReorderMetadataFieldRequest
> = z.object({
  position: z.int().describe("The position of the metadata field."),
});
