/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DatasourceExternalIdsRequest,
  DatasourceExternalIdsRequest$zodSchema,
} from "./datasourceexternalidsrequest.js";
import {
  MetadataFieldDatasourceValuesArray,
  MetadataFieldDatasourceValuesArray$zodSchema,
} from "./metadatafielddatasourcevaluesarray.js";

export type RestoreMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const RestoreMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type RestoreMetadataFieldDatasourceRequest = {
  external_id: string;
  datasource_external_ids_request: DatasourceExternalIdsRequest;
};

export const RestoreMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceRequest
> = z.object({
  datasource_external_ids_request: DatasourceExternalIdsRequest$zodSchema
    .describe("The datasource entry external IDs to restore."),
  external_id: z.string().describe(
    "The external ID of the metadata field to restore the datasource values for.",
  ),
});

export type RestoreMetadataFieldDatasourceResponse =
  | ApiError
  | MetadataFieldDatasourceValuesArray;

export const RestoreMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldDatasourceValuesArray$zodSchema,
]);
