/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldDatasourceValuesArray,
  MetadataFieldDatasourceValuesArray$zodSchema,
} from "./metadatafielddatasourcevaluesarray.js";

export type RestoreMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const RestoreMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type RestoreMetadataFieldDatasourceRequestBody = {
  external_ids?: Array<string> | undefined;
};

export const RestoreMetadataFieldDatasourceRequestBody$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_ids: z.array(z.string()).optional(),
});

export type RestoreMetadataFieldDatasourceRequest = {
  external_id: string;
  RequestBody: RestoreMetadataFieldDatasourceRequestBody;
};

export const RestoreMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() =>
    RestoreMetadataFieldDatasourceRequestBody$zodSchema
  ),
  external_id: z.string().describe(
    "The external ID of the metadata field to restore the datasource values for.",
  ),
});

export type RestoreMetadataFieldDatasourceResponse =
  | ApiError
  | MetadataFieldDatasourceValuesArray;

export const RestoreMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  RestoreMetadataFieldDatasourceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  MetadataFieldDatasourceValuesArray$zodSchema,
]);
