/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 12cfe3c34e03
 */

import * as z from "zod";

export type SchemeCloudinaryAuth = { api_key: string; api_secret: string };

export const SchemeCloudinaryAuth$zodSchema: z.ZodType<SchemeCloudinaryAuth> = z
  .object({
    api_key: z.string(),
    api_secret: z.string(),
  });
