/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DatasourceSearchResult,
  DatasourceSearchResult$zodSchema,
} from "./datasourcesearchresult.js";

export type SearchMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const SearchMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  SearchMetadataFieldDatasourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type SearchMetadataFieldDatasourceResponse =
  | ApiError
  | Array<DatasourceSearchResult>;

export const SearchMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  SearchMetadataFieldDatasourceResponse
> = z.union([
  ApiError$zodSchema,
  z.array(DatasourceSearchResult$zodSchema).describe("search results"),
]);
