/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type SearchMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const SearchMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  SearchMetadataFieldDatasourceGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type SearchMetadataFieldDatasourceRequest = {
  term?: string | undefined;
  max_results?: number | undefined;
};

export const SearchMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  SearchMetadataFieldDatasourceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_results: z.number().int().default(100),
  term: z.string().optional(),
});

export type ResponseBody = {
  field_id?: string | undefined;
  id?: string | undefined;
  value?: string | undefined;
};

export const ResponseBody$zodSchema: z.ZodType<
  ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  field_id: z.string().optional(),
  id: z.string().optional(),
  value: z.string().optional(),
});

export type SearchMetadataFieldDatasourceResponse =
  | ApiError
  | Array<ResponseBody>;

export const SearchMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  SearchMetadataFieldDatasourceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.array(z.lazy(() => ResponseBody$zodSchema)).describe("search results"),
]);
