/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldDatasourceValuesArray,
  MetadataFieldDatasourceValuesArray$zodSchema,
} from "./metadatafielddatasourcevaluesarray.js";

export type SearchDatasourceInMDFieldGlobals = {
  cloud_name?: string | undefined;
};

export const SearchDatasourceInMDFieldGlobals$zodSchema: z.ZodType<
  SearchDatasourceInMDFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * Metadata payload for rule-based inference
 */
export type Payload = {};

export const Payload$zodSchema: z.ZodType<Payload, z.ZodTypeDef, unknown> = z
  .object({}).describe("Metadata payload for rule-based inference");

export type SearchDatasourceInMDFieldRequestBody = {
  payload?: Payload | undefined;
};

export const SearchDatasourceInMDFieldRequestBody$zodSchema: z.ZodType<
  SearchDatasourceInMDFieldRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  payload: z.lazy(() => Payload$zodSchema).optional(),
});

export type SearchDatasourceInMDFieldRequest = {
  external_id: string;
  max_results?: number | undefined;
  term?: string | undefined;
  exact_match?: boolean | undefined;
  RequestBody: SearchDatasourceInMDFieldRequestBody;
};

export const SearchDatasourceInMDFieldRequest$zodSchema: z.ZodType<
  SearchDatasourceInMDFieldRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() => SearchDatasourceInMDFieldRequestBody$zodSchema),
  exact_match: z.boolean().default(false).describe(
    "Whether to search for an exact match.",
  ),
  external_id: z.string().describe(
    "The external ID of the metadata field to search the datasource for.",
  ),
  max_results: z.number().int().default(255).describe(
    "The maximum number of results to return.",
  ),
  term: z.string().describe(
    "The term to search for. can be any substring of the value.",
  ).optional(),
});

export type SearchDatasourceInMDFieldResponse =
  | ApiError
  | MetadataFieldDatasourceValuesArray;

export const SearchDatasourceInMDFieldResponse$zodSchema: z.ZodType<
  SearchDatasourceInMDFieldResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  MetadataFieldDatasourceValuesArray$zodSchema,
]);
