/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CondExp, CondExp$zodSchema } from "./condexp.js";
import { LogicExpUnion, LogicExpUnion$zodSchema } from "./logicexpunion.js";

/**
 * The condition that triggers this metadata rule. Can be either a logical expression (and/or) or an atomic condition.
 */
export type SmdCondition = CondExp | LogicExpUnion;

export const SmdCondition$zodSchema: z.ZodType<
  SmdCondition,
  z.ZodTypeDef,
  unknown
> = z.union([
  CondExp$zodSchema,
  LogicExpUnion$zodSchema,
]).describe(
  "The condition that triggers this metadata rule. Can be either a logical expression (and/or) or an atomic condition.",
);
