/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The active or inactive state.
 */
export const StateEnum = {
  Active: "active",
  Inactive: "inactive",
} as const;
/**
 * The active or inactive state.
 */
export type StateEnum = ClosedEnum<typeof StateEnum>;

export const StateEnum$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The active or inactive state.");
