/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SuccessResponse = { success: boolean };

export const SuccessResponse$zodSchema: z.ZodType<SuccessResponse> = z.object({
  success: z.boolean().describe("Whether the operation was successful."),
});
