/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { MetadataField, MetadataField$zodSchema } from "./metadatafield.js";

export type UpdateMetadataFieldGlobals = { cloud_name?: string | undefined };

export const UpdateMetadataFieldGlobals$zodSchema: z.ZodType<
  UpdateMetadataFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateMetadataFieldRequest = {
  external_id: string;
  metadata_field: MetadataField;
};

export const UpdateMetadataFieldRequest$zodSchema: z.ZodType<
  UpdateMetadataFieldRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string().describe(
    "The external ID of the metadata field to retrieve.",
  ),
  metadata_field: MetadataField$zodSchema,
});

export type UpdateMetadataFieldResponse = MetadataField | ApiError;

export const UpdateMetadataFieldResponse$zodSchema: z.ZodType<
  UpdateMetadataFieldResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  MetadataField$zodSchema,
  ApiError$zodSchema,
]);
