/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldDatasourceValue,
  MetadataFieldDatasourceValue$zodSchema,
} from "./metadatafielddatasourcevalue.js";

export type UpdateMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const UpdateMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * The state of the option.
 */
export const UpdateMetadataFieldDatasourceState = {
  Active: "active",
  Inactive: "inactive",
} as const;
/**
 * The state of the option.
 */
export type UpdateMetadataFieldDatasourceState = ClosedEnum<
  typeof UpdateMetadataFieldDatasourceState
>;

export const UpdateMetadataFieldDatasourceState$zodSchema = z.enum([
  "active",
  "inactive",
]).describe("The state of the option.");

export type UpdateMetadataFieldDatasourceValue = {
  external_id?: string | undefined;
  value?: string | undefined;
  position?: number | undefined;
  state?: UpdateMetadataFieldDatasourceState | undefined;
};

export const UpdateMetadataFieldDatasourceValue$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceValue
> = z.object({
  external_id: z.string().optional(),
  position: z.int().optional(),
  state: UpdateMetadataFieldDatasourceState$zodSchema.optional(),
  value: z.string().optional(),
});

export type UpdateMetadataFieldDatasourceRequestBody = {
  values?: Array<UpdateMetadataFieldDatasourceValue> | undefined;
};

export const UpdateMetadataFieldDatasourceRequestBody$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceRequestBody
> = z.object({
  values: z.array(z.lazy(() => UpdateMetadataFieldDatasourceValue$zodSchema))
    .optional(),
});

export type UpdateMetadataFieldDatasourceRequest = {
  external_id: string;
  RequestBody: UpdateMetadataFieldDatasourceRequestBody;
};

export const UpdateMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceRequest
> = z.object({
  RequestBody: z.lazy(() => UpdateMetadataFieldDatasourceRequestBody$zodSchema),
  external_id: z.string().describe(
    "The external ID of the metadata field to update the datasource for.",
  ),
});

/**
 * datasource updated
 */
export type UpdateMetadataFieldDatasourceResponseBody = {
  values?: Array<MetadataFieldDatasourceValue> | undefined;
};

export const UpdateMetadataFieldDatasourceResponseBody$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceResponseBody
> = z.object({
  values: z.array(MetadataFieldDatasourceValue$zodSchema).optional(),
}).describe("datasource updated");

export type UpdateMetadataFieldDatasourceResponse =
  | ApiError
  | UpdateMetadataFieldDatasourceResponseBody;

export const UpdateMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceResponse
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => UpdateMetadataFieldDatasourceResponseBody$zodSchema),
]);
