/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataRuleResponse,
  MetadataRuleResponse$zodSchema,
} from "./metadataruleresponse.js";
import {
  MetadataRuleUpdate,
  MetadataRuleUpdate$zodSchema,
} from "./metadataruleupdate.js";

export type UpdateMetadataRuleGlobals = { cloud_name?: string | undefined };

export const UpdateMetadataRuleGlobals$zodSchema: z.ZodType<
  UpdateMetadataRuleGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateMetadataRuleRequest = {
  external_id: string;
  metadata_rule_update: MetadataRuleUpdate;
};

export const UpdateMetadataRuleRequest$zodSchema: z.ZodType<
  UpdateMetadataRuleRequest
> = z.object({
  external_id: z.string().describe(
    "The unique identifier of the metadata rule.",
  ),
  metadata_rule_update: MetadataRuleUpdate$zodSchema,
});

export type UpdateMetadataRuleResponse = ApiError | MetadataRuleResponse;

export const UpdateMetadataRuleResponse$zodSchema: z.ZodType<
  UpdateMetadataRuleResponse
> = z.union([
  ApiError$zodSchema,
  MetadataRuleResponse$zodSchema,
]);
