/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 449307857b00
 */

import * as z from "zod";
import {
  DatasourceValueInput,
  DatasourceValueInput$zodSchema,
} from "./datasourcevalueinput.js";

export type UpdateDatasourceRequest = {
  values?: Array<DatasourceValueInput> | undefined;
};

export const UpdateDatasourceRequest$zodSchema: z.ZodType<
  UpdateDatasourceRequest
> = z.object({
  values: z.array(DatasourceValueInput$zodSchema).optional(),
});
