/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataFieldDatasourceValuesArray,
  MetadataFieldDatasourceValuesArray$zodSchema,
} from "./metadatafielddatasourcevaluesarray.js";
import {
  UpdateDatasourceRequest,
  UpdateDatasourceRequest$zodSchema,
} from "./updatedatasourcerequest.js";

export type UpdateMetadataFieldDatasourceGlobals = {
  cloud_name?: string | undefined;
};

export const UpdateMetadataFieldDatasourceGlobals$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateMetadataFieldDatasourceRequest = {
  external_id: string;
  update_datasource_request: UpdateDatasourceRequest;
};

export const UpdateMetadataFieldDatasourceRequest$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceRequest
> = z.object({
  external_id: z.string().describe(
    "The external ID of the metadata field to update the datasource for.",
  ),
  update_datasource_request: UpdateDatasourceRequest$zodSchema.describe(
    "The updated datasource values.",
  ),
});

export type UpdateMetadataFieldDatasourceResponse =
  | ApiError
  | MetadataFieldDatasourceValuesArray;

export const UpdateMetadataFieldDatasourceResponse$zodSchema: z.ZodType<
  UpdateMetadataFieldDatasourceResponse
> = z.union([
  ApiError$zodSchema,
  MetadataFieldDatasourceValuesArray$zodSchema,
]);
