/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ValueUnion1 = string | number;

export const ValueUnion1$zodSchema: z.ZodType<
  ValueUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

/**
 * The value(s) to apply to the metadata field. Can be string, number, or array of strings/numbers depending on the field type.
 */
export type ValueUnion2 = string | number | Array<string | number>;

export const ValueUnion2$zodSchema: z.ZodType<
  ValueUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.array(z.union([
    z.string(),
    z.number(),
  ])),
]).describe(
  "The value(s) to apply to the metadata field. Can be string, number, or array of strings/numbers depending on the field type.",
);

/**
 * Whether to set as default value (default) or append to existing values (append). Default is default.
 */
export const ValueExpMode$zodSchema = z.enum([
  "default",
  "append",
]).describe(
  "Whether to set as default value (default) or append to existing values (append). Default is default.",
);

export type ValueExpMode = z.infer<typeof ValueExpMode$zodSchema>;

/**
 * Specifies a value to apply to the metadata field.
 */
export type ValueExp = {
  value: string | number | Array<string | number>;
  mode?: ValueExpMode | undefined;
};

export const ValueExp$zodSchema: z.ZodType<ValueExp, z.ZodTypeDef, unknown> = z
  .object({
    mode: ValueExpMode$zodSchema.default("default"),
    value: z.union([
      z.string(),
      z.number(),
      z.array(z.union([
        z.string(),
        z.number(),
      ])),
    ]),
  }).describe("Specifies a value to apply to the metadata field.");
