/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Whether to set as default value (default) or append to existing values (append). Default is default.
 */
export const ValueExpMode = {
  Default: "default",
  Append: "append",
} as const;
/**
 * Whether to set as default value (default) or append to existing values (append). Default is default.
 */
export type ValueExpMode = ClosedEnum<typeof ValueExpMode>;

export const ValueExpMode$zodSchema = z.enum([
  "default",
  "append",
]).describe(
  "Whether to set as default value (default) or append to existing values (append). Default is default.",
);

export type ValueUnion1 = string | number;

export const ValueUnion1$zodSchema: z.ZodType<ValueUnion1> = z.union([
  z.string(),
  z.number(),
]);

/**
 * The value(s) to apply to the metadata field. Can be string, number, or array of strings/numbers depending on the field type.
 */
export type ValueUnion2 = string | number | Array<string | number>;

export const ValueUnion2$zodSchema: z.ZodType<ValueUnion2> = z.union([
  z.string(),
  z.number(),
  z.array(z.union([
    z.string(),
    z.number(),
  ])),
]).describe(
  "The value(s) to apply to the metadata field. Can be string, number, or array of strings/numbers depending on the field type.",
);

/**
 * Specifies a value to apply to the metadata field.
 */
export type ValueExp = {
  value: string | number | Array<string | number>;
  mode?: ValueExpMode | undefined;
};

export const ValueExp$zodSchema: z.ZodType<ValueExp> = z.object({
  mode: ValueExpMode$zodSchema.default("default").describe(
    "Whether to set as default value (default) or append to existing values (append). Default is default.",
  ),
  value: z.union([
    z.string(),
    z.number(),
    z.array(z.union([
      z.string(),
      z.number(),
    ])),
  ]).describe(
    "The value(s) to apply to the metadata field. Can be string, number, or array of strings/numbers depending on the field type.",
  ),
}).describe("Specifies a value to apply to the metadata field.");
